### ISSUE TITLE
Wrong cursor postions for  16*4 displays 

### ISSUE THREAD

**Issue by Riekusb** [johnrickman/LiquidCrystal_I2C#64]
void LiquidCrystal_I2C::setCursor(uint8_t col, uint8_t row){
	int row_offsets[] = { 0x00, 0x40, 0x14, 0x54 };  **<<<<<< I Think  it should not be fixed here**
	if ( row > _numlines ) {
		row = _numlines-1;    // we count rows starting w/0
	}
	command(LCD_SETDDRAMADDR | (col + row_offsets[row]));
}

**Comment by ModestasK** [comment]
The repo has been archive and moved to gitlab (the URL in the readme does not really work though)
I doubt this bug will be fixed (unless you fork and fix it yourself)

**Comment by Riekusb** [comment]
OK I will do that.
